# Prepare pdf.html for vivliostyle

library(rvest)
library(xml2)
pdf <- read_html("pdf.html")
stylesheet_nodes <- html_elements(pdf, "link[rel=stylesheet]")
xml_attr(stylesheet_nodes[1], "href") <- "source/custom.css"
xml2::xml_remove(stylesheet_nodes[-1])
setup_node <- html_elements(pdf, ".setup")
xml2::xml_remove(setup_node)
# Do I want to remove all div.cell? NO
# xml2::xml_remove(html_nodes(pdf, ".cell"))
ojs_script_node <- html_element(pdf, "script[src='index_files/libs/quarto-ojs/quarto-ojs-runtime.js']")
xml2::xml_remove(ojs_script_node)
module_nodes <- html_elements(pdf, "script[type=module]")
xml2::xml_remove(module_nodes)
ojs_module_node <- html_element(pdf, "script[type=ojs-module-contents]")
xml2::xml_remove(ojs_module_node)
js_nodes <- html_elements(pdf, "script[type='text/javascript']")
xml2::xml_remove(js_nodes)
json_node <- html_elements(pdf, "script[type='application/json']")
xml2::xml_remove(json_node)
nav_node <- html_element(pdf, ".navigation")
xml2::xml_remove(nav_node)
xml2::xml_remove(html_nodes(pdf, "script#quarto-html-after-body"))
write_html(pdf, "pdf.html")

# system("vivliostyle preview pdf.html")
output_file <- file.path(output_dir, paste0(city_string, "-city-scan.pdf"))
system(glue("vivliostyle build pdf.html -o {output_file}"))
